### ISSUE TITLE
program gets into an infinite loop

### ISSUE THREAD

**Issue by EdenBelouadah** [AAnoosheh/ToDayGAN#31]
Hello, 
I'm trying to run your pre-trained model on my test dataset, to see the effect on it. 
This is the content of the subfolders:

```
(vodkaplus) eden@eden-xps:~/ToDayGAN$ ls checkpoints/robotcar_night2day/
150_net_D0.pth  opt.txt

(vodkaplus) eden@eden-xps:~/ToDayGAN$ ls datasets/tmp/*
datasets/tmp/test0:

datasets/tmp/test1:
hamburhnight1.jpg
```

The program just doesn't pass this step: 

```
(my_env) eden@eden-xps:~/ToDayGAN$ python test.py  \
    --phase test  --which_epoch 150  \
    --serial_test  \
    --dataroot ./datasets/tmp  \
    --name robotcar_night2day  \
    --n_domains 2  \
    --loadSize 512

/home/eden/anaconda3/envs/my_env/lib/python3.8/site-packages/torch/cuda/__init__.py:143: UserWarning: 
NVIDIA GeForce RTX 3050 Ti Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3050 Ti Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
------------ Options -------------
aspect_ratio: 1.0
autoencode: False
batchSize: 1
checkpoints_dir: ./checkpoints
dataroot: ./datasets/22
display_id: 0
display_port: 8097
display_single_pane_ncols: 0
display_winsize: 256
fineSize: 256
gpu_ids: [0]
how_many: 50
input_nc: 3
isTrain: False
loadSize: 512
max_dataset_size: inf
nThreads: 2
n_domains: 2
name: robotcar_night2day
ndf: 64
netD_n_layers: 4
netG_n_blocks: 9
netG_n_shared: 0
ngf: 64
no_flip: False
norm: instance
output_nc: 3
phase: test
reconstruct: False
resize_or_crop: resize_and_crop
results_dir: ./results/
serial_test: True
show_matrix: False
use_dropout: False
which_epoch: 150
-------------- End ----------------
/home/eden/anaconda3/envs/my_env/lib/python3.8/site-packages/torchvision/transforms/transforms.py:287: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
```

I also notices cuda warning.
Could you please help?
Thank you

**Comment by EdenBelouadah** [comment]
I figured out that the problem was coming from the cuda version. I fixed it with

`pip3 install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html`

Just a remark, the train0 folder shouldn't be empty. Otherwise the program crashes. 

Thank you again
